### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by benzo8** [bpoxy/plex-tvdb-alt-orderer#1]
OS: Linux mediaserver 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Python: 3.8.10

```
pip install plex-tvdb-alt-orderer
Collecting inquirer (from plex-tvdb-alt-orderer)
  Downloading inquirer-3.1.3-py3-none-any.whl (18 kB)
Requirement already satisfied: plexapi in ./.local/lib/python3.8/site-packages (from plex-tvdb-alt-orderer) (4.11.1)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting tvdb-v4-official (from plex-tvdb-alt-orderer)
  Downloading tvdb_v4_official-1.1.0-py3-none-any.whl (3.8 kB)
Collecting validators (from plex-tvdb-alt-orderer)
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting blessed>=1.19.0 (from inquirer->plex-tvdb-alt-orderer)
  Downloading blessed-1.20.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 11.3 MB/s eta 0:00:00
Collecting python-editor>=1.0.4 (from inquirer->plex-tvdb-alt-orderer)
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting readchar>=3.0.6 (from inquirer->plex-tvdb-alt-orderer)
  Downloading readchar-4.0.5-py3-none-any.whl (8.5 kB)
Requirement already satisfied: requests in ./.local/lib/python3.8/site-packages (from plexapi->plex-tvdb-alt-orderer) (2.27.1)
Requirement already satisfied: decorator>=3.4.0 in ./.local/lib/python3.8/site-packages (from validators->plex-tvdb-alt-orderer) (5.1.1)
Collecting wcwidth>=0.1.4 (from blessed>=1.19.0->inquirer->plex-tvdb-alt-orderer)
  Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: six>=1.9.0 in ./.local/lib/python3.8/site-packages (from blessed>=1.19.0->inquirer->plex-tvdb-alt-orderer) (1.16.0)
Requirement already satisfied: setuptools>=41.0 in ./.local/lib/python3.8/site-packages (from readchar>=3.0.6->inquirer->plex-tvdb-alt-orderer) (62.3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.8/site-packages (from requests->plexapi->plex-tvdb-alt-orderer) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.8/site-packages (from requests->plexapi->plex-tvdb-alt-orderer) (2022.5.18.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.local/lib/python3.8/site-packages (from requests->plexapi->plex-tvdb-alt-orderer) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.8/site-packages (from requests->plexapi->plex-tvdb-alt-orderer) (3.3)
Building wheels for collected packages: progress, validators
  Building wheel for progress (setup.py) ... done
  Created wheel for progress: filename=progress-1.6-py3-none-any.whl size=9613 sha256=251d82dea8e7e7374097d1be80fe5dcd74cc8b121c746b114bab5531d1d76e55
  Stored in directory: /home/john/.cache/pip/wheels/bb/01/5a/c916509df9b12c6465864251dbe826def8e31a16fa7da54f08
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=f51739ca2d6cd5b64dc0219ecbcebb4c9cadbf99e36b2a438415823118afe4ca
  Stored in directory: /home/john/.cache/pip/wheels/19/09/72/3eb74d236bb48bd0f3c6c3c83e4e0c5bbfcbcad7c6c3539db8
Successfully built progress validators
Installing collected packages: wcwidth, tvdb-v4-official, python-editor, progress, validators, termcolor, readchar, blessed, inquirer, plex-tvdb-alt-orderer
Successfully installed blessed-1.20.0 inquirer-3.1.3 plex-tvdb-alt-orderer-0.2.1 progress-1.6 python-editor-1.0.4 readchar-4.0.5 termcolor-2.3.0 tvdb-v4-official-1.1.0 validators-0.20.0 wcwidth-0.2.6
john@mediaserver ~ % plex-tvdb-alt-orderer
Traceback (most recent call last):
  File "/home/john/.local/bin/plex-tvdb-alt-orderer", line 5, in <module>
    from plex_tvdb_alt_orderer.main import main
  File "/home/john/.local/lib/python3.8/site-packages/plex_tvdb_alt_orderer/main.py", line 104, in <module>
    def update_plex(season: int, plex_episodes: list[Episode], tvdb_episodes: list[dict]):
TypeError: 'type' object is not subscriptable
```

**Comment by bpoxy** [comment]
Fixed in v0.2.2.
