### ISSUE TITLE
KeyError: 'image' when running the script 

### ISSUE THREAD

**Issue by kvalle22** [bpoxy/plex-tvdb-alt-orderer#8]
It occurs when I try to apply alternate order to Entire Series, it also happens if I try season by season. It succesfully changes the name but still get the error 
```
[?] Select the order to apply: Sagas
   Aired Order
   DVD Order
   Absolute Order
 > Sagas

[?] Select the season to update: Entire Series
 > Entire Series
   Season 1
   Season 2
   Season 3
   Season 4
   Season 5
   Season 6
   Season 7
   Season 8
   Season 9

Updating Plex |##############################  | 154/162Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Scripts\plex-tvdb-alt-orderer.exe\__main__.py", line 7, in <module>
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\plex_tvdb_alt_orderer\main.py", line 48, in main
    update_plex(season, plex_show, tvdb_episodes, tvdb_seasons)
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\plex_tvdb_alt_orderer\main.py", line 186, in update_plex
    if tvdb_season["image"]:
       ~~~~~~~~~~~^^^^^^^^^
KeyError: 'image'
```

![image](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/26128231/4e377409-cbff-4a5b-b168-2fcb8df8fdea)
For example, I have successfully updated the name till season 4. I'll run the script get the same error but still the name of season 5 will be updated
```
[?] Select the order to apply: Sagas
   Aired Order
   DVD Order
   Absolute Order
 > Sagas

[?] Select the season to update: Season 5
   Entire Series
   Season 1
   Season 2
   Season 3
   Season 4
 > Season 5
   Season 6
   Season 7
   Season 8
   Season 9

Updating Plex |#############################   | 10/11Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Scripts\plex-tvdb-alt-orderer.exe\__main__.py", line 7, in <module>
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\plex_tvdb_alt_orderer\main.py", line 48, in main
    update_plex(season, plex_show, tvdb_episodes, tvdb_seasons)
  File "C:\Users\PMS\AppData\Local\Programs\Python\Python311\Lib\site-packages\plex_tvdb_alt_orderer\main.py", line 186, in update_plex
    if tvdb_season["image"]:
       ~~~~~~~~~~~^^^^^^^^^
KeyError: 'image'
```
![image](https://github.com/bpoxy/plex-tvdb-alt-orderer/assets/26128231/0993a4bc-fdbc-40b3-8a8f-02ecc03c1c76)

**Comment by bpoxy** [comment]
Fixed in v0.3.1.
